### ISSUE TITLE
build failed on alpine for a static binary use github workflow?

### ISSUE THREAD

**Issue by zw963** [kostya/lexbor#31]
Please check workflow log here.

https://github.com/crystal-china/myip/actions/runs/4955663882/jobs/8865266920

BTW, i tried install cmake with both candidate.

```yml
- name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.16.x"
```

```yml
    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
```

Both of them not work.

thanks.
